# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c200e5e7a114143a70c4a46ff3b1e0c2a4bb02fc8bbe3f7205c24d77a115ae7cbc343c49c1f4d0866a0a8ad4a51b4e65d37d942e273ac86fb7f31ec306fda4a1

test:
  secret_key_base: b5cdb3df47f8e837da7cf808a031fce606572004085b349c445c99eef3860f7e9af51459f5c6107b414c67131620374a9777a7fe13e02bc7f4f24d3492b561dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
